@communityId = e772a4d1-98a3-44d9-a1a5-9dad9c5de59e

### Kullanıcı Giriş Testi (Önce buna bas!)
# @name login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "tayanc@metu.edu.tr",
  "password": "Sifre123!"
}

### Token'ı Otomatik Yakala (Kritik Satır!)
@authToken = {{login.response.body.session.access_token}}

### Korumalı Topluluk Oluşturma Testi (Otomatik Token)
POST http://localhost:8080/api/communities
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "METU Motorsport",
  "description": "Hız ve mühendislik bir arada.",
  "category": "Teknik"
}

### Etkinlik Oluştur (Başarılı - 201 Expected)
POST http://localhost:8080/api/events/{{communityId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "C++ ile Oyun Geliştirme Workshop",
  "description": "Unreal Engine temellerini öğreniyoruz. Laptopunuzu getirmeyi unutmayın!",
  "starts_at": "2026-03-20T18:00:00Z",
  "location": "METU Teknokent - Co-Working Space",
  "capacity": 30
}

### 1. Etkinlikleri Listele (Katılacağımız Etkinliğin ID'sini Buradan Alacağız)
# @name listEvents
GET http://localhost:8080/api/events
Authorization: Bearer {{authToken}}

### Değişken Tanımlama (listEvents cevabındaki ilk id'yi alır)
@eventId = {{listEvents.response.body.0.id}}

### 2. Etkinliğe Katıl (İlk Sefer - 201 Expected)
POST http://localhost:8080/api/events/join/{{eventId}}
Authorization: Bearer {{authToken}}

### 3. Tekrar Katılmayı Dene (Hata Testi - 409 Expected)
POST http://localhost:8080/api/events/join/{{eventId}}
Authorization: Bearer {{authToken}}

### 4. Etkinlik Katılımcılarını Gör (200 Expected)
GET http://localhost:8080/api/events/participants/{{eventId}}
Authorization: Bearer {{authToken}}